// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZP1UPGHLH9K4Rr-aaa7Kga-VUZS5kGy8',
    appId: '1:507376148980:web:01f5ca946669d0bccd99a1',
    messagingSenderId: '507376148980',
    projectId: 'kg-prueba',
    authDomain: 'kg-prueba.firebaseapp.com',
    databaseURL: 'https://kg-prueba-default-rtdb.firebaseio.com',
    storageBucket: 'kg-prueba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHdLdbp8OZacMxqQVqFivzCI9ElIEMZRM',
    appId: '1:507376148980:android:d43274374445bfcccd99a1',
    messagingSenderId: '507376148980',
    projectId: 'kg-prueba',
    databaseURL: 'https://kg-prueba-default-rtdb.firebaseio.com',
    storageBucket: 'kg-prueba.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZP1UPGHLH9K4Rr-aaa7Kga-VUZS5kGy8',
    appId: '1:507376148980:web:01f5ca946669d0bccd99a1',
    messagingSenderId: '507376148980',
    projectId: 'kg-prueba',
    authDomain: 'kg-prueba.firebaseapp.com',
    databaseURL: 'https://kg-prueba-default-rtdb.firebaseio.com',
    storageBucket: 'kg-prueba.firebasestorage.app',
  );

}